
name: Build

on:
  #push:
  #  branches: [ '**' ]
  #  tags-ignore: [ '**' ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      os:
        type: choice
        required: true
        default: 'windows-latest'
        options:
        - macos-latest
        - ubuntu-latest
        - windows-latest

jobs:
  build:
    name: Build
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Clone Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Packages
        run: npm run install

      - name: Validate
        run: npm run validate

      - name: Build Python Server
        run: npm run build python

      - name: Build Electron
        shell: bash
        run: |
          npx electron-builder install-app-deps
          case "${{ github.event.inputs.os }}" in
            macos*)
              CSC_IDENTITY_AUTO_DISCOVERY=false npx electron-builder --mac --universal --publish never -c.mac.identity=null
              ;;
            ubuntu*)
              npx electron-builder --linux appimage --x64 --publish never
              npx electron-builder --linux snap --x64 --publish never
              ;;
            windows*)
              npx electron-builder --win --x64 --arm64 --publish never
              ;;
          esac

      - name: Upload MacOS
        if: ${{ startsWith(github.event.inputs.os,'macos') }}
        uses: Actions/upload-artifact@v4
        with:
          name: Netron-MacOS
          path: dist/*.dmg
          #dist/pypi/*.whl
          retention-days: 1

      - name: Upload Ubuntu
        if: ${{ startsWith(github.event.inputs.os,'ubuntu') }}
        uses: Actions/upload-artifact@v4
        with:
          name: Netron-Ubuntu
          path: dist/*.AppImage
          # dist/pypi/*.whl
          retention-days: 1

      - name: Upload Windows
        if: ${{ startsWith(github.event.inputs.os,'windows') }}
        uses: Actions/upload-artifact@v4
        with:
          name: Netron-Windows
          path: dist/*.exe
          # dist/pypi/*.whl
          retention-days: 1
